---

- name: Config nginx nginx-siteavailable
  template:
    src: "default.j2"
    dest: /etc/nginx/sites-available/

- name: Start nginx service
  service:
    name: nginx
    state: started

- name: run nginx on boot
  service:
    name: nginx
    enabled: yes