---

- hosts: localhost
  tasks:
  - set_fact: project_name="{{project_name}}"
  - copy: "content='project_name: {{project_name}}\nsftp_password: {{sftp_password}}\ndomain_name: {{domain_name}}\nversion: {{version}}' dest='/root/install-wordpress/{{project_name}}.yml'"
  - name: Ensure /{{project_name}}/ exits
    stat:
      path: /root/install-wordpress/{{project_name}}/
    register: stat_result

  - name: Create the file, if it doesnt exist already
    file:
      path: /root/install-wordpress/{{project_name}}/
      state: directory
    when: stat_result.stat.exists == false

  vars_prompt:
  - name: "project_name"
    prompt: "Project name"
    private: no
  - name: "sftp_password"
    prompt: "SFTP password for dev user"
    private: yes
    confirm: yes    
    salt_size: 7
  - name: "domain_name"
    prompt: "Domain name of project"
    private: no
  - name: "version"
    prompt: "version php"
    private: no

- include: target.yml
